const weatherApiKey = '20a88b66783ca7c64bc8bbdd37993c46';
const metric = 'metric';
const imperial = 'imperial';
const celsius = 'C';
const fahrenheit = 'F';
const degree = '\u00b0';
const iconUrlPrefix = 'https://openweathermap.org/img/wn/';
const iconUrlSuffix = '@2x.png';
final List<String> majorCities = [
  'New York City',
  'Los Angeles',
  'Chicago',
  'Houston',
  'Phoenix',
  'Philadelphia',
  'San Antonio',
  'San Diego',
  'Dallas',
  'San Jose',
  'Austin',
  'Jacksonville',
  'San Francisco',
  'Columbus',
  'Indianapolis',
  'Fort Worth',
  'Charlotte',
  'Seattle',
  'Denver',
  'El Paso',
  'Detroit',
  'Washington, D.C.',
  'Boston',
  'Memphis',
  'Nashville',
  'Baltimore',
  'Oklahoma City',
  'Las Vegas',
  'Louisville',
  'Milwaukee',
  'Albuquerque',
  'Tucson',
  'Fresno',
  'Sacramento',
  'Kansas City',
  'Mesa',
  'Atlanta',
  'Colorado Springs',
  'Omaha',
  'Raleigh',
  'Miami',
  'Cleveland',
  'Tulsa',
  'Oakland',
  'Minneapolis',
  'Wichita',
  'Arlington',
  'Bakersfield',
  'Tampa',
  'Aurora',
  'Anaheim',
  'Honolulu',
  'Riverside',
  'Corpus Christi',
  'Lexington',
  'Stockton',
  'St. Louis',
  'Saint Paul',
  'Cincinnati',
  'Pittsburgh',
  'Greensboro',
  'Anchorage',
  'Plano',
  'Henderson',
  'Lincoln',
  'Buffalo',
  'Jersey City',
  'Chula Vista',
  'Fort Wayne',
  'Orlando',
  'St. Petersburg',
  'Laredo',
  'Madison',
  'Gilbert',
  'Norfolk',
  'Glendale',
  'Reno',
  'Hialeah',
  'Chattanooga',
  'Boise',
  'Richmond',
  'Frisco',
  'Baton Rouge',
  'Des Moines',
  'Spokane',
  'Tacoma',
  'San Bernardino',
  'Modesto',
  'Fontana',
  'Santa Clarita',
  'Oxnard',
  'Moreno Valley',
  'Vancouver',
  'Surrey',
  'Mississauga',
  'Montreal',
  'Toronto',
  'Vancouver',
  'Calgary',
  'Edmonton',
  'Ottawa',
  'Halifax',
  'Quebec City',
  'Winnipeg',
  'Victoria',
  'Hamilton',
  'London',
  'Manchester',
  'Birmingham',
  'Glasgow',
  'Edinburgh',
  'Dublin',
  'Belfast',
  'Cardiff',
  'Liverpool',
  'Leeds',
  'Sheffield',
  'Nottingham',
  'Newcastle upon Tyne',
  'Bristol',
  'Brighton',
  'Southampton',
  'Plymouth',
  'Aberdeen',
  'Inverness',
  'Stirling',
];
